#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Raphaël Mor
"""Write both layout documents from the QMK sources.

Two targets, one command, because they must not disagree:

  ../../../keyboard-layout/README.md  the layout, no board in it, plus docs/*.svg
  users/raphaelmor/README.md          what is true of this Corne and this firmware

Each file keeps everything outside

    <!-- layout:begin -->
    <!-- layout:end -->

so the prose you write around the generated block survives a regeneration.

    python3 tools/kle_docs.py            # write both
    python3 tools/kle_docs.py --check    # exit 1 and name anything stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import kle_export as E  # noqa: E402
import kle_render as R  # noqa: E402

QMK_README = E.USERSPACE / "README.md"
KLE_JSON = E.USERSPACE / "corne-v4-1-ramo.json"
LAYOUT_REPO = E.USERSPACE.parents[2] / "keyboard-layout"
BEGIN = "<!-- layout:begin -->"
END = "<!-- layout:end -->"
GENERATED = ("<!-- Generated by qmk_userspace/users/raphaelmor/tools/kle_docs.py. "
             "Do not hand-edit this section; edit around it. -->")

LAYOUT_PREAMBLE = """# Colemak + Hands Down Promethium

A 36-key layout, on two alpha bases that share one set of layers.

**[Hands Down Promethium](https://github.com/moutis/HandsDown)** is the base I
type on. **Colemak** is kept alongside it because it is what everything else in
the world assumes, and because switching back costs one double tap.

The layers follow **[Miryoku](https://github.com/manna-harbour/miryoku)**: hold a
thumb, get a layer, and the payload sits on the hand opposite the thumb that
activated it. On top of that sit combos for the letters and glyphs that have no
home on 36 keys, and adaptive keys that rewrite same-finger bigrams as you roll
them.

Nothing below names a switch. Everything is described by position, so it holds
for any 3x5 + 3 split.

<!-- Write whatever you like here. Only the block below is generated. -->
"""

QMK_PREAMBLE_MARKER = "# HANDS DOWN GOLD and COLEMAK MIRYOKU CUSTOM SETUP FOR CORNE"


def render_layers(source: dict) -> dict[str, str]:
    """Layer prefix -> SVG text, one board per file."""
    return {prefix: R.render(E.one_board(source, enum, prefix))
            for enum, prefix in source["layers"]}


def section(body: str) -> str:
    return "\n".join([BEGIN, "", GENERATED, "", body, "", END])


def splice(existing: str, body: str, fallback_header: str = "") -> str:
    """Replace the marked region, or create the file around it."""
    start, end = existing.find(BEGIN), existing.find(END)
    if start == -1 or end == -1:
        head = existing.rstrip() or fallback_header.rstrip()
        return head + "\n\n" + section(body) + "\n"
    return existing[:start] + section(body) + existing[end + len(END):]


def read_or_empty(path: Path) -> str:
    return path.read_text() if path.exists() else ""


def planned_files(source: dict, layout_repo: Path | None) -> dict[Path, str]:
    """Every path this run would write, and what it would put there."""
    # The KLE document's Notes field is built from the same sections as the two
    # READMEs, so it goes stale for the same reasons. Cover it here or --check
    # will report "up to date" while corne-v4-1-ramo.json still holds old text.
    files: dict[Path, str] = {
        QMK_README: splice(read_or_empty(QMK_README),
                           E.qmk_doc(source),
                           QMK_PREAMBLE_MARKER),
        KLE_JSON: E.serialize(E.build_document(source)),
    }
    if layout_repo is None:
        return files

    body = E.layout_doc(source, "docs/layer-{prefix}.svg")
    files[layout_repo / "README.md"] = splice(
        read_or_empty(layout_repo / "README.md"), body, LAYOUT_PREAMBLE)
    for prefix, svg in render_layers(source).items():
        files[layout_repo / "docs" / f"layer-{prefix.lower()}.svg"] = svg
    return files


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--layout-repo", type=Path, default=LAYOUT_REPO,
                    help=f"default {LAYOUT_REPO}")
    ap.add_argument("--check", action="store_true",
                    help="report what is stale and change nothing")
    ap.add_argument("--gold", action="store_true",
                    help="render Hands Down Gold instead of Promethium")
    args = ap.parse_args()

    repo = args.layout_repo if args.layout_repo.is_dir() else None
    if repo is None:
        print(f"kle_docs: {args.layout_repo} is not there — writing the QMK "
              f"README only", file=sys.stderr)

    try:
        source = E.read_all(promethium=not args.gold)
        files = planned_files(source, repo)
    except E.ExportError as err:
        print(f"kle_docs: {err}", file=sys.stderr)
        return 1

    stale = [p for p, text in files.items()
             if not p.exists() or p.read_text() != text]
    if args.check:
        for path in stale:
            print(f"out of date: {path}")
        print("up to date" if not stale
              else f"{len(stale)} file(s) need `python3 tools/kle_docs.py`")
        return 1 if stale else 0

    for path, text in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    print(f"wrote {len(files)} file(s), {len(stale)} changed")
    for path in stale:
        print(f"  {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
