TAP_DANCE_ENABLE = yes
MOUSEKEY_ENABLE = yes
AUTO_SHIFT_ENABLE = no
CAPS_WORD_ENABLE = yes
CONSOLE_ENABLE = yes
COMBO_ENABLE = yes

INTROSPECTION_KEYMAP_C += raphaelmor.c

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = yes

